# Generated by Django 5.1.6 on 2025-03-04 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='blocked_students',
            field=models.ManyToManyField(blank=True, related_name='blocked_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
